version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: scadabr-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scadabr
      MYSQL_USER: scadabr
      MYSQL_PASSWORD: scadabr
      TZ: America/Sao_Paulo
    command:
      --default-time-zone=America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  scadabr:
    build: .
    image: scadabr:1.2
    container_name: scadabr
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - scadabr_uploads:/usr/local/tomcat/webapps/ScadaBR/uploads


volumes:
  mysql_data:
  scadabr_uploads:
